-- MySQL Script generated by MySQL Workbench
-- 01/17/17 00:25:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Globant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Globant` DEFAULT CHARACTER SET utf8 ;
USE `Globant` ;

-- -----------------------------------------------------
-- Table `mydb`.`Paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Globant`.`Paises` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Alpha3` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Globant`.`Provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Globant`.`Provincias` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `Paises_idPais` INT NOT NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  `Abreviatura` VARCHAR(10) NOT NULL,
  `Km2` INT NOT NULL,
  `Capital` VARCHAR(45) NOT NULL,
  `Ciudad mas grande` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvincia`),
  INDEX `fk_Provincias_Paises_idx` (`Paises_idPais` ASC),
  CONSTRAINT `fk_Provincias_Paises`
    FOREIGN KEY (`Paises_idPais`)
    REFERENCES `Globant`.`Paises` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Globant`.`Vientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Globant`.`Vientos` (
  `idVientos` INT NOT NULL AUTO_INCREMENT,
  `Velocidad` INT NOT NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVientos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Globant`.`Atmosfera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Globant`.`Atmosfera` (
  `idAtmosfera` INT NOT NULL AUTO_INCREMENT,
  `Humedad` INT NOT NULL,
  `Presion` INT NOT NULL,
  `Visibilidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAtmosfera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Globant`.`Pronosticos Extendidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Globant`.`PronosticosExtendidos` (
  `idPronosticosExtendidos` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Dia` VARCHAR(45) NOT NULL,
  `Maxima` INT NOT NULL,
  `Minima` INT NOT NULL,
  PRIMARY KEY (`idPronosticosExtendidos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Globant`.`Dia Actual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Globant`.`DiaActual` (
  `idDiaActual` INT NOT NULL AUTO_INCREMENT,
  `Dia` VARCHAR(8) NULL,
  `Fecha` VARCHAR(10) NOT NULL,
  `Temperatura` INT NOT NULL,
  `Vientos_idVientos` INT NOT NULL,
  `Atmosfera_idAtmosfera` INT NOT NULL,
  `PronosticosExtendidos_idPronosticosExtendidos` INT NOT NULL,
  PRIMARY KEY (`idDiaActual`),
  INDEX `fk_DiaActual_Vientos1_idx` (`Vientos_idVientos` ASC),
  INDEX `fk_DiaActual_Atmosfera1_idx` (`Atmosfera_idAtmosfera` ASC),
  INDEX `fk_DiaActual_PronosticosExtendidos1_idx` (`PronosticosExtendidos_idPronosticosExtendidos` ASC),
  CONSTRAINT `fk_DiaActual_Vientos1`
    FOREIGN KEY (`Vientos_idVientos`)
    REFERENCES `Globant`.`Vientos` (`idVientos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dia Actual_Atmosfera1`
    FOREIGN KEY (`Atmosfera_idAtmosfera`)
    REFERENCES `Globant`.`Atmosfera` (`idAtmosfera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dia Actual_PronosticosExtendidos1`
    FOREIGN KEY (`PronosticosExtendidos_idPronosticosExtendidos`)
    REFERENCES `Globant`.`PronosticosExtendidos` (`idPronosticosExtendidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
